version: "3"

tasks:
  generate:
    aliases:
      - migrate
    desc: "Generate code from proto files"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations